baseURL = "http://connectplaytest.co.nz"
disableLanguages = []
disqusShortname = "educenter"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Connectplay"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright @ 2020 Connectplay ltd All rights reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[menu.footer]]
URL = ""
name = "Services"
[[menu.footer]]
URL = "device"
name = "Routers"
[[menu.footer]]
URL = "neuron"
name = "TR-069 Device Management(ACS)"
[[menu.footer]]
URL = "https://neuron.nz"
name = "Neuron ACS"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
hasChildren = true
name = "Our Services"
weight = 2
[[menu.main]]
URL = "device"
name = "Routers"
parent = "Our Services"
[[menu.main]]
URL = "neuron"
name = "TR-069 Device Management(ACS)"
parent = "Our Services"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Ground Floor/584, Great South Road, Ellerslie, 1051"
author = "Connectplay Ltd"
contact_form_action = "#"
email = "support@connectplay.co.nz"
google_analitycs_id = ""
logo = "images/logos/logonew.png"
mobile = "09-589-1350"
top_header = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDQhYwAKBz54w4vtqdKkTEYzSk0mcClCDQ&amp"
map_latitude = "-36.8960217"
map_longitude = "174.801127"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = ""
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/Connectplay-Ltd-473536229331979/"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/connectplaynz?lang=en"
title = "twitter"
[[params.social]]
icon = "ti-github"
link = "https://git.connectplay.co.nz/"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/connectplay"
title = "linkedin"
[[params.terms]]
URL = "terms"
name = "Terms and Conditions"
weight = 2
[[params.tr069]]
URL = "tr069"
name = "Terms "
weight = 2
