######################## default configuration ####################
baseURL = "http://examplesite.org"
title = "Connectplay"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Customers"
URL = "customers"
weight = 2

[[menu.main]]
weight = 3
name = "Our Services"
hasChildren = true

    [[menu.main]]
  parent = "Our Services"
  name = "Routers"
  URL = "event"

  [[menu.main]]
  parent = "Our Services"
  name = "TR-069 Device Management(ACS)"
  URL = "neuron"
  
[[menu.main]]
name = "Blog"
URL = "blog"
weight = 4
  
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5


# footer menu

[[menu.footer]]
name = "Services"
URL = ""


[[menu.footer]]
name = "Routers"
URL = "event"

[[menu.footer]]
name = "TR-069 Device Management(ACS)"
URL = "neuron"



#################### default parameters ################################
[params]
logo = "images/logos/logo2.png"
# Meta data
#description = "Enhancing Broadband Comapny"
author = "Connectplay"
# contact info
address = "Ground Floor/584, Great South Road, Ellerslie, 1051"
mobile = "09-589-1350"
email = "support@connectplay.co.nz"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDQhYwAKBz54w4vtqdKkTEYzSk0mcClCDQ&amp"
map_latitude = "-36.8960217"
map_longitude = "174.801127"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/Connectplay-Ltd-473536229331979/"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/connectplaynz?lang=en"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://git.connectplay.co.nz/"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/connectplay"




[[params.terms]]
name = "Terms and Conditions"
URL = "terms"
weight = 2

[[params.tr069]]
name = "Terms "
URL = "tr069"
weight = 2

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright @ 2020 Connectplay ltd All rights reserved"





